name: New Content Release

on:
  # push:
  #   branches: ci
  workflow_dispatch:

env:
  DIST_DIR: "config"

jobs:      
  generate_content_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout distrib
        uses: actions/checkout@v3
        with:
          repository: actionquake/distrib
          path: ${{ env.DIST_DIR }}

      - name: Adjust timestamps
        working-directory: ${{ env.DIST_DIR }}
        run: python ${{ env.DIST_DIR }}/scripts/git-tools/git-restore-mtime

      - name: Zip game content to pkz
        working-directory: ${{ env.DIST_DIR }}/baseaq
        run: |
          for makepkz in pak0 pak1; do
            cd ${makepkz}
            zip -r ../${makepkz}.pkz * && cd ..
            rm -rf ${makepkz}/
          done

      - name: Copy premade pkz's into action
        working-directory: ${{ env.DIST_DIR }}
        run: |
          mv paks/zz_billboard_textures.pkz action/zz_billboard_textures.pkz

      - name: Download all library files for Windows, Linux and Linux ARM
        run: |
          for FILE in tng-win-64 tng-lin-x86_64 tng-lin-arm64 tng-darwin-x86_64 tng-darwin-arm64; \
          do wget -qnv https://github.com/actionquake/aq2-tng/releases/latest/download/${FILE}.zip \
          && unzip -o ${FILE}.zip -d ${{ env.DIST_DIR }}/baseaq/ \
          && unzip -o ${FILE}.zip -d ${{ env.DIST_DIR }}/action/ \
          ; done

      - name: Make all libraries executable
        run: |
          chmod +x ${{ env.DIST_DIR }}/baseaq/game*
          chmod +x ${{ env.DIST_DIR }}/action/game*

      - name: Generate dist files
        run: |
          cd ${{ env.DIST_DIR }} && zip -r aqtion-content.zip versions baseaq/ action/

      - name: Generate archive
        uses: actions/upload-artifact@v3
        with:
          name: aq-content-only
          path: |
            ${{ env.DIST_DIR }}/aqtion-content.zip

      - name: 'Post-build cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
